### ISSUE TITLE
[B] Przeniesienie modeli encji

### ISSUE THREAD

**Issue by NataliaCichonska** [mbrunka/zwinne-project#3]
Jak w instrukcji 3.2

**Comment by mbrunka** [comment]
# Student zrobiony
Encje, interfejs zostały zrobione przez zemnie. 

## Pozostało do zrobienia encje: projekt i zadanie

**Comment by mbrunka** [comment]
Zrobiłem podstawowe pola dla wszystkich encji, twoim zadaniem jest dodanie do nich komunikatów na podstawie PDF oraz klasy Student do pozostałych dwóch class w com.project.model

**Comment by mbrunka** [comment]
Zrobione, ale nie ma jeszcze CRUD zadań
