### ISSUE TITLE
[B+F] Refresh token

### ISSUE THREAD

**Issue by NataliaCichonska** [mbrunka/zwinne-project#8]

**Comment by mbrunka** [comment]
expire date: access token 5 min i refresh token 7 dni

można w razie czego łatwo zmienić.

{{base_url}}/api/v1/auth/refresh jest jako POST. Postman zaaktualizowany

**Comment by mbrunka** [comment]
Nie widziałem że oboje jesteśmy przypięci do taska, dlatego pozmieniałem nazwę ale odczarowane.  Backend gotowy.

**Comment by NataliaCichonska** [comment]
zamknięte
