### ISSUE TITLE
[B] CRUD do projektów

### ISSUE THREAD

**Issue by NataliaCichonska** [mbrunka/zwinne-project#9]
Dla prowadzącego: wyświetlanie listy swoich projektów dodawania projektów + wyświetlanie hasła do projektu, usuwanie projektów, modyfikowanie szczegółów projektu
Dla studenta: Zapisywanie się do projektu poprzez podanie hasła, wyświetlanie listy swoich projektów

**Comment by mbrunka** [comment]
Chyba zrobione, mogą pojawiać się bugi oraz może brakować jakieś funkcjonalności

**Comment by mbrunka** [comment]
Brakuje możliwości wyświetlania  przez studenta projektów w których jest
